version: '3'
services:
  libgdx-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8085"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3309"
